[[section-introduction-and-goals]]
== Introduction and Goals
This is a mock to test how to deploy the documentation.
[role="arc42help"]
****
Describes the relevant requirements and the driving forces that software architects and development team must consider. These include

* underlying business goals, essential features and functional requirements for the system
* quality goals for the architecture
* relevant stakeholders and their expectations
****
LoMap intends to be an easy-to-use tool for people to create, customize, and share personal maps filling them with the places they live.

This map application allows the user to create multiple different maps that are empty.

The user then will create locations or photos for the places they want and add them to any of their own maps. You can add friends or groups and share these location with them so that they show on their maps for them to comment or give a score

=== Requirements Overview


[role="arc42help"]
****
.Contents
Short description of the functional requirements, driving forces, extract (or abstract)
of requirements. Link to (hopefully existing) requirements documents
(with version number and information where to find it).

.Motivation
From the point of view of the end users a system is created or modified to
improve support of a business activity and/or improve the quality.

.Form
Short textual description, probably in tabular use-case format.
If requirements documents exist this overview should refer to these documents.

Keep these excerpts as short as possible. Balance readability of this document with potential redundancy w.r.t to requirements documents.
****

* Users must be able to create different maps. One user could have more than one map

* Users must be able to add locations to their own maps. Initially shops, bars, restaurants, sight and monuments.

* Users must be able to add reviews to locations. Scores, comments and pictures could be added to a location.

* Locations could be shared with other users, a friend or a group of friends.

* User's data will be extracted and stored into SOLID PODS. Users' locations information will also be stored in the user' POD.

* Locations will be printed in a map. It will have filters. Initially category, friends, and different types of locations.



=== Quality Goals

[role="arc42help"]
****
.Contents
The top three (max five) quality goals for the architecture whose fulfillment is of highest importance to the major stakeholders. We really mean quality goals for the architecture. Don't confuse them with project goals. They are not necessarily identical.

.Motivation
You should know the quality goals of your most important stakeholders, since they will influence fundamental architectural decisions. Make sure to be very concrete about these qualities, avoid buzzwords.
If you as an architect do not know how the quality of your work will be judged …

.Form
A table with quality goals and concrete scenarios, ordered by priorities
****
[options="header",cols="1,2,2"]
|===
|Priority|Description|Expectations
|1|Privacy|Users' data will only be accessed when permissions have been granted.
|2|Decentralization|Users' data will be accessed and stored using Solid PODS.
|3|Usability|The application must be intuitive so a novice user should be able to navigate in less than 10 minutes.
|4|Accesibility|The web application will comply with WCAG 2.0 at level AAA.
|===

=== Stakeholders

[role="arc42help"]
****
.Contents
Explicit overview of stakeholders of the system, i.e. all person, roles or organizations that

* should know the architecture
* have to be convinced of the architecture
* have to work with the architecture or with code
* need the documentation of the architecture for their work
* have to come up with decisions about the system or its development

.Motivation
You should know all parties involved in development of the system or affected by the system.
Otherwise, you may get nasty surprises later in the development process.
These stakeholders determine the extent and the level of detail of your work and its results.

.Form
Table with role names, person names, and their expectations with respect to the architecture and its documentation.
****

[options="header",cols="1,2,2,2"]
|===
|Role/Name|Contact|Description|Expectations
|Developers|Mario Pérez Fernández (uo283720@uniovi.es) +
Ivan Vega Gracía (uo276670@uniovi.es) +
Silvia Suárez Prendes (uo277412@uniovi.es) +
Sara María Ramírez Pérez (uo276188@uniovi.es) +
Elías Llera García-Riaño (uo271407@uniovi.es) +
Andrés Álvarez Murillo (uo278249@uniovi.es)|Group of students in charge of developing the project.|Deliver a fucntional version that meets the specified requirements.
|Teachers|Pablo González González (gonzalezgpablo@uniovi.es) +
José Emilio Labra Gayo (labra@uniovi.es) |Professors of the course in charge of supervising and guide the development team.| Evaluate the final delivery and help through the process.
|Users| |Final users of LoMap. |Use the application, and they should be satisfied by it.
|Solid|https://forum.solidproject.org|Specification to store users' data in a decentralized manner. | Gain decentralization of data.
|Compaines |Inrupt +
Empathy |Compaines involved in the Solid challenge. | Evaluate the projects and decide a winner for the challenge
|===
