[[section-system-scope-and-context]]
== System Scope and Context

LoMap is a software system designed to provide users with personalized maps about places and local businesses in their city. 
The maps will be under the full control of the users and the shared information will be stored in personal pod according to the SOLID project.

Another feature of the application will be to allow places to create their own space, like a digital version of their physical place.

[role="arc42help"]
****





=== Business Context

The system will allow users to add locations in different categories, see places and information about those places taken from their friends, show the locations in a map window, add review scores, comments... 

The user is able to add locations in different categories, add review scores, comments, or pictures about the added places. It also will be possible to manage from the application the information that is accessible with other users, like their friends or group of friends and to see the map with filters like by category, friends... 


The system is structured in two parts: a frontend and a backend. The user only interfaces with the frontend, which in turn interfaces with the backend, which then works with the Solid Pod provider and the database serve the data the frontend might need.

[role="arc42help"]
****



=== Technical Context

The frontend of the application is made with React. It also uses Redux.

Techology:
    - TypeScript as programming language
    - MongoDB as Database
    - React Redux
    - Axios
    - Postman



[role="arc42help"]
****

.Motivation
Many stakeholders make architectural decision based on the technical interfaces between the system and its context. Especially infrastructure or hardware designers decide these technical interfaces.

.Form
E.g. UML deployment diagram describing channels to neighboring systems,
together with a mapping table showing the relationships between channels and input/output.

****

**<Diagram or Table>**

**<optionally: Explanation of technical interfaces>**

**<Mapping Input/Output to Channels>**
