[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****

Technology decisions
This are the technologies that we have decided to use, some of them may vary in future iterations of the poyect:
 * SOLID Pods for security
 * TypeScript as programming language
 * MongoDb as our DMBS
 * Redux using React as UI
 * Axios
 * Postman

Design decisions:
The general design of our project has two main parts, connected using a facade:
 * Webapp (frontend): with views and connections to the SOLID pods and to the RestAPI facade
 * RestAPI (backend): controls the acess to the database and works as a microservice

Quality decisions
The main quality attributes that we will focus on are the following:
 * Privacy: SOLID Pods will be used to ensure that user's data is not compromised
 * Decentralization
 * Usability: We intend to make an app that can perform its task in an efficient and correct way
 * Accessibility: Inexperienced users will be able to navigate and use the app




