[[section-solution-strategy]]
== Solution Strategy


[role="arc42help"]
****
.Contents
A short summary and explanation of the fundamental decisions and solution strategies, that shape the system's architecture. These include

* technology decisions
* decisions about the top-level decomposition of the system, e.g. usage of an architectural pattern or design pattern
* decisions on how to achieve key quality goals
* relevant organizational decisions, e.g. selecting a development process or delegating certain tasks to third parties.

.Motivation
These decisions form the cornerstones for your architecture. They are the basis for many other detailed decisions or implementation rules.

.Form
Keep the explanation of these key decisions short.

Motivate what you have decided and why you decided that way,
based upon your problem statement, the quality goals and key constraints.
Refer to details in the following sections.
****

=== Technology decisions
This are the technologies that we have decided to use, some of them may vary in future iterations of the poyect:

* SOLID PODs for security
* TypeScript as programming language
* MongoDb as our DMBS
* Redux using React as UI
* Axios
* Postman
* Chakra UI (for the implementation of the views)


=== Design decisions:
The general design of our project has two main parts, connected using a facade:

 * Webapp (frontend): with views and connections to the SOLID pods and to the RestAPI facade
 * RestAPI (backend): controls the acess to the database and works as a microservice


=== Quality decisions
The main quality attributes that we will focus on are the following:
[options="header",cols="1,2,2"]
|===
|Quality goal|Scenario|Solution approach
|Privacy|Any user using our application will feel their data is secure | We will use SOLID Pods to ensure that user's data is not compromised.
|Usability|All users, regardless of their level, are able to navigate and use the application correctly|We will use UX conventions to ensure that the app has its components presented in a familiar way
|Accessibility|All users, regardless of their physical and mental capabilities should be able to use the application.|We are going to use external accesibility tools.
|===







