[[section-runtime-view]]
== Runtime View


[role="arc42help"]
****
.Contents
The runtime view describes concrete behavior and interactions of the system’s building blocks in form of scenarios from the following areas:

* important use cases or features: how do building blocks execute them?
* interactions at critical external interfaces: how do building blocks cooperate with users and neighboring systems?
* operation and administration: launch, start-up, stop
* error and exception scenarios

Remark: The main criterion for the choice of possible scenarios (sequences, workflows) is their *architectural relevance*. It is *not* important to describe a large number of scenarios. You should rather document a representative selection.

.Motivation
You should understand how (instances of) building blocks of your system perform their job and communicate at runtime.
You will mainly capture scenarios in your documentation to communicate your architecture to stakeholders that are less willing or able to read and understand the static models (building block view, deployment view).

.Form
There are many notations for describing scenarios, e.g.

* numbered list of steps (in natural language)
* activity diagrams or flow charts
* sequence diagrams
* BPMN or EPCs (event process chains)
* state machines
* ...

****

=== User registration
* _Alice enters the system for the first time and registers her personal data to create an account and start ussing the webapp.
* _The user will be able to fill a form with their data that is saved on their private POD.


=== User Login
* _Bob already registered on the system and wants to log in with their user and password to acess the webapp.
* _The user will be able to fill a form with their user and password that will be sent to the server to be authenticated and allow or deny access.


=== Adding a Location
* _Alice wants to add the location restaurant to the webapp and see it on the map.
* _The user will be able to select a location category and the coordinates for the location to be placed and seen on their map.


=== Reviewing information about a place
* _Bob wants to select a friend's added location and see the pictures they added to it.
* _Locations made public or shared with the user will be able to be accesed by the user to review aditional information that the creator added to the place.


=== Changing privacy settings
* _Alice doesn't want their friends seeing the locations she added to the map so she acesses the settings of the webapp to disable sharing them.
* _The different settings about what information on the places and the user is accesible by their friends will be able to be changed, giving different options for each parameter.


=== User adds a new friend
* A user navigating the app may select the button to search and add a new friend request
** If they are not friends already, the user will add the friend to their friend list
** If they are friends already, it will remain the same


=== User deletes a friend
* A user can remove a friend from their friend list
** If they select a friend from their list, they can choose to remove them and all places shared with them will no longer be shared


=== User creates a friend group
* A user can create a group of friends. This group is composed only of user friends and is managed by the user as if it was one friend.
** The user can decide to share a location with the group and all participant will have that location shared too
** The user can decide remove something  they shared from the group and all participants will have it removed
** Users can add or remove friend from the group and all shared places with them will be removed
** Users can delete a group they created. All places shared with the group will no longer be shared with any of the participants
