[[section-design-decisions]]
== Design Decisions


=== Technologies

.Typescript
Reason:: Typescript and JavaScript were the two main options for the language of the system. Because of the number of resources available to implement a React application with Typescript, we decided to choose it over Javascript.
Pros::
* Good integration with the technology stack.
* Good option for web applications.
Cons::
* No member of the team is familiar with it.

.React
Reason:: React is one of the most used if not the number one option to develop the front-end of web applications. We decided to choose it over Angular due to the number of already implemented components available.
Pros::
* Lots of resources to learn.
* Many libraries.
Cons::
* Managing states can be troublesome.

.Redux
Reason:: Redux is a pattern that facilitates state management. Since we consider this a con of React, we think it can be a good way of solving it.
Pros::
* Easy debugging and testing.
* Predictability.
Cons::
* If we end up not using several data sources, it could add overhead for no real reason.

.Node EXPRESS
Reason:: Since we decided to use Typescript and React-Redux, using Node is mandatory and the sample project uses EXPRESS, we decided using for the final application as well to make configuration easier.

.MongoDB
Reason:: The alternative was using a MySQL server, but since the integration with a Node application is much more complicated and the newer versions of Mongo have relational operations, we decided to choose the second option.
Pros::
* Scalability
* Decentralization of the application
* Flexibility
Cons::
* Although relational operations are available, they are not as optimized as in a traditional database.

.Chakra UI
Reason:: the weight of the package was optimal and it is intuitive.
Pros:: 
* It has a great variety of components and they are very useful.
* Accessibility.
* Easy-to-understand documentation.
Cons::
* It is not possible to style some of the components it provides.
* We have not found many examples of using the component templates it offers.


=== Architecture
.SOLID pods connection to the RestAPI
Reason:: The application will be divided into two big modules: WebApp (front-end) and API (back-end). We have the option of connecting the SOLID pods to any of the two modules. Our decision is to connect it to the RestAPI.
Pros::
* Business logic isolation in the WebAPP.
Cons::
* Not many examples of SOLID Pod access from the server side.

.Local database used as cache
Reason:: After developing the first prototype of our application, we realised that around 80% of the response time of the server was due to the delay in retrieving data from the user´s Pod. In order to improve performance, we decided to store all the information in the user´s pod and keep it as the "master" information, but to store a copy in a local database and use it when accessing shared resources (information from other users' pods).
Pros::
* Improved performance.
* Data redundancy.
* The user privacy is not affected, only data that the user wants to share is stored.
Cons::
* Only improves performance when accessing other users´ data.
* Adds complexity to the RestAPI.
image:

.Location filters in the WebAPP
Reason:: In order to reduce the number of calls to the RestAPI and consequently the number of calls to external sites (Pod Providers), the filters will be executed in the WebAPP cache (store module).
Pros::
* Reduced response time when applying filters.
Cons::
* Implementation of some business logic in the WebAPP.

